name: Dry Run CloudFormation Deploy

on:
  push:
    branches:
      - dry-run-cfn-test

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Run CloudFormation dry run
        run: |
          aws cloudformation deploy \
            --template-file cf_templates/eks-cluster.yaml \
            --stack-name dryrun-eks-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-execute-changeset \
            --parameter-overrides \
              EnvName=dev \
              ClusterName=eks-dev-cluster \
              NodeGroupName=eks-dev-nodegroup \
              DesiredCapacity=2 \
              MaxSize=3 \
              MinSize=1 \
              VpcId=vpc-xxxxxxxx \
              SubnetIds="subnet-aaaaaaa,subnet-bbbbbbb"
