name: CloudFormation Dry Run

on:
  workflow_dispatch:
  push:
    branches:
      - dry-run-cfn-test

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: CloudFormation Template Lint
        run: |
          echo "Validating CloudFormation Template..."
          aws cloudformation validate-template --template-body file://infra/templates/eks-cluster.yml
